#!/usr/bin/env python
"""Render headline result tables as Markdown directly from committed ``results/*.csv``.

Every table is a deterministic function of the CSVs — **no number is hand-entered**. Each table
carries a provenance comment (source CSV + its SHA-256 + the run manifests it derives from), so the
report can be regenerated and audited. Writes ``docs/paper/_generated_tables.md`` (or stdout).

    python -m wildfire_marl.reproducibility.build_report_tables
    python -m wildfire_marl.reproducibility.build_report_tables --out docs/paper/_generated_tables.md

Only CSVs that exist are rendered, and only the columns present in each CSV — so a retired/renamed
CSV degrades to a skipped table rather than a crash.

Ported from V1 (``legacy_v1/scripts/build_report_tables.py``) in Phase 0; the rendering mechanism
is unchanged. ``TABLES`` starts empty: V2 tables are registered as the phases that produce their
CSVs land (Phase 4 baselines, Phase 9 transfer, Phase 10 ablations). The V1 table definitions and
their CSVs stay frozen in ``legacy_v1/`` and are never rendered as V2 results.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import pandas as pd

RESULTS = Path("results")

# (csv, title, columns, provenance-note). Columns are intersected with what the CSV actually has.
# Registered per phase as V2 result CSVs are produced — see the module docstring.
TABLES: list[tuple[str, str, list[str], str]] = []


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _fmt(v: object) -> str:
    if isinstance(v, float):
        return "nan" if v != v else f"{v:.3f}"  # noqa: PLR0124 (NaN check)
    return str(v)


def _to_md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    rows = ["| " + " | ".join(cols) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    for _, row in df.iterrows():
        rows.append("| " + " | ".join(_fmt(row[c]) for c in cols) + " |")
    return "\n".join(rows)


def render_table(csv_name: str, title: str, cols: list[str], provenance: str) -> str | None:
    csv = RESULTS / csv_name
    if not csv.exists():
        return None
    df = pd.read_csv(csv)
    use = [c for c in cols if c in df.columns]
    df = df[use]
    out = [
        f"### {title}",
        "",
        f"<!-- source: {csv.as_posix()} | sha256: {_sha256(csv)} | provenance: {provenance} -->",
        "",
        _to_md(df),
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=None, help="Write to this file instead of stdout.")
    args = ap.parse_args()

    blocks = [
        "<!-- AUTO-GENERATED by wildfire_marl.reproducibility.build_report_tables — "
        "DO NOT EDIT BY HAND. -->",
        "<!-- Regenerate: python -m wildfire_marl.reproducibility.build_report_tables "
        "--out docs/paper/_generated_tables.md -->",
        "",
        "# Regenerated Result Tables (authoritative)",
        "",
    ]
    rendered = 0
    for csv_name, title, cols, prov in TABLES:
        block = render_table(csv_name, title, cols, prov)
        if block is None:
            blocks.append(f"<!-- skipped: results/{csv_name} not found -->\n")
        else:
            blocks.append(block)
            rendered += 1
    if not TABLES:
        blocks.append("<!-- no V2 tables registered yet (Phase 0) — see module docstring -->\n")

    text = "\n".join(blocks)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"Wrote {args.out} ({rendered} tables)", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
