"""Multi-agent actor-critic and value mixing neural network architectures.

Implements shared-parameter CNN policy/critic networks for MAPPO and QMIX.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


class CustomSmallCNN(nn.Module):
    """Small CNN extractor to process spatial inputs without dimension crashes."""

    def __init__(self, in_channels: int = 8, features_dim: int = 64):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        # Assuming crop size is 9x9: output is 64 * 9 * 9 = 5184
        self.fc = nn.LazyLinear(features_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = torch.flatten(x, start_dim=1)
        x = F.relu(self.fc(x))
        return x


class MAPPOActor(nn.Module):
    """Decentralized actor policy using shared parameter CNN."""

    def __init__(self, in_channels: int = 8, action_dim: int = 6, features_dim: int = 64):
        super().__init__()
        self.extractor = CustomSmallCNN(in_channels=in_channels, features_dim=features_dim)
        self.action_head = nn.Linear(features_dim, action_dim)

    def forward(self, obs: torch.Tensor, action_mask: torch.Tensor | None = None) -> torch.Tensor:
        """Returns action logits. If action_mask is provided, invalid actions are masked."""
        features = self.extractor(obs)
        logits = self.action_head(features)
        if action_mask is not None:
            # Mask out invalid actions by subtracting infinity
            # action_mask is boolean: True for valid, False for invalid
            fill_value = -1e9
            logits = torch.where(
                action_mask, logits, torch.tensor(fill_value, device=logits.device)
            )
        return logits


class MAPPOCritic(nn.Module):
    """Centralized critic mapping global grid state to state value V(s)."""

    def __init__(self, in_channels: int = 5, features_dim: int = 128):
        super().__init__()
        # Global state is HxW (32x32)
        self.conv1 = nn.Conv2d(in_channels, 32, kernel_size=3, stride=2, padding=1)  # 16x16
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1)  # 8x8
        self.fc1 = nn.LazyLinear(features_dim)
        self.value_head = nn.Linear(features_dim, 1)

    def forward(self, global_state: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.conv1(global_state))
        x = F.relu(self.conv2(x))
        x = torch.flatten(x, start_dim=1)
        x = F.relu(self.fc1(x))
        return self.value_head(x)


class QMIXAgent(nn.Module):
    """Decentralized Q-value network for QMIX."""

    def __init__(self, in_channels: int = 8, action_dim: int = 6, features_dim: int = 64):
        super().__init__()
        self.extractor = CustomSmallCNN(in_channels=in_channels, features_dim=features_dim)
        self.q_head = nn.Linear(features_dim, action_dim)

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        features = self.extractor(obs)
        return self.q_head(features)


class QMIXMixingNetwork(nn.Module):
    """Centralized QMIX mixing network with positive weights generated by hypernetworks."""

    def __init__(self, num_agents: int = 3, state_dim: int = 128, mix_hidden: int = 32):
        super().__init__()
        self.num_agents = num_agents
        self.mix_hidden = mix_hidden
        self.state_dim = state_dim

        # Global state extractor: compresses 32x32 global state into state_dim
        # Global state has 5 channels
        self.state_extractor = nn.Sequential(
            nn.Conv2d(5, 32, kernel_size=3, stride=2, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.LazyLinear(state_dim),
            nn.ReLU(),
        )

        # Hypernetwork 1: outputs Weight 1 of shape [num_agents, mix_hidden]
        self.hyper_w1 = nn.Linear(state_dim, num_agents * mix_hidden)
        # Hypernetwork 2: outputs Weight 2 of shape [mix_hidden, 1]
        self.hyper_w2 = nn.Linear(state_dim, mix_hidden * 1)

        # Biases for the layers
        self.hyper_b1 = nn.Linear(state_dim, mix_hidden)
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, mix_hidden),
            nn.ReLU(),
            nn.Linear(mix_hidden, 1),
        )

    def forward(self, agent_qs: torch.Tensor, global_state: torch.Tensor) -> torch.Tensor:
        """
        Args:
            agent_qs: Individual Q-values of shape [batch_size, num_agents]
            global_state: Global environment states of shape [batch_size, 5, 32, 32]
        """
        bs = agent_qs.size(0)
        state_feats = self.state_extractor(global_state)

        # Weight 1: reshape and make non-negative (using abs or exp)
        w1_raw = self.hyper_w1(state_feats)
        w1 = torch.abs(w1_raw.view(bs, self.num_agents, self.mix_hidden))

        # Bias 1
        b1 = self.hyper_b1(state_feats).view(bs, 1, self.mix_hidden)

        # Weight 2: shape [mix_hidden, 1]
        w2_raw = self.hyper_w2(state_feats)
        w2 = torch.abs(w2_raw.view(bs, self.mix_hidden, 1))

        # Bias 2
        b2 = self.hyper_b2(state_feats).view(bs, 1, 1)

        # Forward pass through mixed layers
        # Input layer: agent_qs of shape [batch_size, 1, num_agents]
        x = agent_qs.unsqueeze(1)
        hidden = F.elu(torch.bmm(x, w1) + b1)  # [bs, 1, mix_hidden]
        out = torch.bmm(hidden, w2) + b2  # [bs, 1, 1]
        return out.squeeze(-1).squeeze(-1)  # [bs]
